version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=azurrodneyyy
      - MONGO_INITDB_ROOT_PASSWORD=9k8cGYOdOu5G3W6M
